// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    organizer: "Nature Lovers Club",
    title: "Nature Photography Workshop",
    description:
      "🌿 **Welcome to the Nature Photography Workshop!** 📸\n\nJoin us for an immersive experience where you'll learn advanced techniques from expert photographers. This workshop is designed for all skill levels, and you'll have the opportunity to capture stunning images in a beautiful natural setting.\n\nBring your camera and enthusiasm for an unforgettable experience. Get ready to explore the wonders of nature through your lens! 🌳",
    location: "Batam",
    venue: "https://maps.app.goo.gl/6NqtyQo48aVK19Nu9",
    imageUrl:
      "https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    eventDate: "2024-07-01",
    startTime: "09:00:00",
    endTime: "12:00:00",
    availableSeat: 5,
    seatLimit: 500,
    isFree: true,
    ticketTypes: [
      {
        name: "Free",
        description: "Free entry",
        price: 0,
        seatLimit: 500,
        availableSeat: 5,
      },
    ],
    eventCategory: "Sport",
  },
  {
    id: 2,
    organizer: "Nature Lovers Club",
    title: "Nature Photography Workshop",
    description:
      "🌿 **Nature Photography Workshop** 📸\n\nEnhance your photography skills in our Nature Photography Workshop. This event offers hands-on training and guidance from professional photographers, allowing you to perfect your techniques and capture the beauty of nature.\n\nIdeal for both beginners and seasoned photographers looking to refine their skills. Join us and take your nature photography to the next level! 🌼",
    location: "Batam",
    venue: "https://maps.app.goo.gl/6NqtyQo48aVK19Nu9",
    imageUrl:
      "https://images.pexels.com/photos/1547813/pexels-photo-1547813.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    //dateTime: "Saturday, June 25, 2024 | 10:00 AM - 2:00 PM",
    eventDate: "2024-07-15",
    startTime: "09:00:00",
    endTime: "17:00:00",
    availableSeat: 10,
    seatLimit: 100,
    isFree: false,
    ticketTypes: [
      {
        name: "vip",
        description: "vip",
        price: 300000,
        seatLimit: 50,
        availableSeat: 3,
      },
      {
        name: "reguler",
        description: "reguler",
        price: 70000,
        seatLimit: 100,
        availableSeat: 5,
      },
    ],
    eventCategory: "Sport",
  },
  {
    id: 3,
    organizer: "Tech Innovators",
    title: "Technology Conference",
    description:
      "🚀 **Technology Conference 2024** 🖥️\n\nJoin industry leaders and innovators at our Technology Conference. This event features keynote speeches, panel discussions, and networking opportunities with top professionals in the tech industry.\n\nDiscover the latest trends, tools, and technologies that are shaping the future. Don't miss out on this opportunity to stay ahead in the tech world! 💡",
    location: "Batam",
    venue: "https://maps.app.goo.gl/63mvVL8EBkoFf7PU9",
    imageUrl:
      "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    eventDate: "2024-07-15",
    startTime: "09:00:00",
    endTime: "17:00:00",
    availableSeat: 50,
    seatLimit: 500,
    isFree: false,
    ticketTypes: [
      {
        name: "vip",
        description: "vip",
        price: 800000,
        seatLimit: 800,
        availableSeat: 50,
      },
      {
        name: "reguler",
        description: "reguler",
        price: 40000,
        seatLimit: 500,
        availableSeat: 40,
      },
    ],
    eventCategory: "Technology",
  },
  {
    id: 4,
    organizer: "Nature Lovers Club",
    title: "Nature Photography Workshop",
    description:
      "🌿 **Join Our Nature Photography Workshop!** 📸\n\nDive into the world of nature photography with our comprehensive workshop. Learn from seasoned photographers and improve your skills in capturing stunning nature images.\n\nThis workshop is perfect for all levels, from beginners to advanced photographers seeking to enhance their techniques. Get ready for a day of creativity and inspiration! 🌸",
    location: "Batam",
    venue: "https://maps.app.goo.gl/63mvVL8EBkoFf7PU9",
    imageUrl:
      "https://images.pexels.com/photos/1547813/pexels-photo-1547813.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    eventDate: "2024-07-15",
    startTime: "09:00:00",
    endTime: "17:00:00",
    availableSeat: 30,
    seatLimit: 100,
    isFree: false,
    ticketTypes: [
      {
        name: "vip",
        description: "vip",
        price: 750000,
        seatLimit: 500,
        availableSeat: 58,
      },
      {
        name: "reguler",
        description: "reguler",
        price: 60000,
        seatLimit: 100,
        availableSeat: 52,
      },
    ],
    eventCategory: "Sport",
  },
  {
    id: 5,
    organizer: "Tech Innovators",
    title: "Technology Conference",
    description:
      "🚀 **Explore the Future at the Technology Conference** 🖥️\n\nDon't miss our upcoming Technology Conference, where you'll engage with leading experts and discover groundbreaking advancements in the tech world.\n\nThis event includes sessions on cutting-edge topics, product demos, and plenty of networking opportunities. Be part of the innovation! 💡",
    location: "Batam",
    venue: "https://maps.app.goo.gl/63mvVL8EBkoFf7PU9",
    imageUrl:
      "https://images.pexels.com/photos/2774556/pexels-photo-2774556.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    eventDate: "2024-07-15",
    startTime: "09:00:00",
    endTime: "17:00:00",
    availableSeat: 20,
    seatLimit: 100,
    isFree: false,
    ticketTypes: [
      {
        name: "vip",
        description: "vip",
        price: 800000,
        seatLimit: 100,
        availableSeat: 45,
      },
      {
        name: "reguler",
        description: "reguler",
        price: 50000,
        seatLimit: 500,
        availableSeat: 65,
      },
    ],
    eventCategory: "Technology",
  },
  {
    id: 6,
    organizer: "Nature Lovers Club",
    title: "Nature Photography Workshop",
    description:
      "🌿 **Nature Photography Workshop Experience** 📸\n\nExperience the thrill of nature photography with our workshop designed for photographers of all levels. Gain insights from experienced photographers and explore new techniques to capture the essence of nature in your photos.\n\nJoin us for a day filled with learning and inspiration. Let your creativity flourish in the great outdoors! 🌺",
    location: "Batam",
    venue: "https://maps.app.goo.gl/63mvVL8EBkoFf7PU9",
    imageUrl:
      "https://images.pexels.com/photos/3225517/pexels-photo-3225517.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1",
    eventDate: "2024-07-15",
    startTime: "09:00:00",
    endTime: "17:00:00",
    availableSeat: 50,
    seatLimit: 150,
    isFree: false,
    ticketTypes: [
      {
        name: "vip",
        description: "vip",
        price: 900000,
        seatLimit: 200,
        availableSeat: 75,
      },
      {
        name: "reguler",
        description: "reguler",
        price: 45000,
        seatLimit: 100,
        availableSeat: 85,
      },
    ],
    eventCategory: "Sport",
  },
];
